//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSSielse
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClsConsultaDeudaPeticion", Namespace="http://schemas.datacontract.org/2004/07/WSCobranzaSIELSE")]
    public partial class ClsConsultaDeudaPeticion : object
    {
        
        private string AgenciaEntidadConsultaField;
        
        private string ClaveUsuarioField;
        
        private string DatoConsultaField;
        
        private System.DateTime FechaConsultaField;
        
        private string IdentificadorEntidadConsultaField;
        
        private string MedioPagoEntidadConsultaField;
        
        private int TipoConsultaField;
        
        private string UsuarioConsultaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AgenciaEntidadConsulta
        {
            get
            {
                return this.AgenciaEntidadConsultaField;
            }
            set
            {
                this.AgenciaEntidadConsultaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ClaveUsuario
        {
            get
            {
                return this.ClaveUsuarioField;
            }
            set
            {
                this.ClaveUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DatoConsulta
        {
            get
            {
                return this.DatoConsultaField;
            }
            set
            {
                this.DatoConsultaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime FechaConsulta
        {
            get
            {
                return this.FechaConsultaField;
            }
            set
            {
                this.FechaConsultaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdentificadorEntidadConsulta
        {
            get
            {
                return this.IdentificadorEntidadConsultaField;
            }
            set
            {
                this.IdentificadorEntidadConsultaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MedioPagoEntidadConsulta
        {
            get
            {
                return this.MedioPagoEntidadConsultaField;
            }
            set
            {
                this.MedioPagoEntidadConsultaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TipoConsulta
        {
            get
            {
                return this.TipoConsultaField;
            }
            set
            {
                this.TipoConsultaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UsuarioConsulta
        {
            get
            {
                return this.UsuarioConsultaField;
            }
            set
            {
                this.UsuarioConsultaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClsConsultaDeudaRespuesta", Namespace="http://schemas.datacontract.org/2004/07/WSCobranzaSIELSE")]
    public partial class ClsConsultaDeudaRespuesta : object
    {
        
        private string CodigoComprobanteField;
        
        private int CodigoMensajeRetornoConsultaField;
        
        private string CodigoSuministroField;
        
        private string DetalleConsultaField;
        
        private string DireccionClienteField;
        
        private string DistritoClienteField;
        
        private System.DateTime FechaEmisionField;
        
        private System.DateTime FechaRegistroConsultaField;
        
        private System.DateTime FechaVencimientoField;
        
        private string IdentificadorEntidadConsultaField;
        
        private string IdentificadorTransaccionField;
        
        private string MensajeRetornoConsultaField;
        
        private decimal MontoAPagarConsultaField;
        
        private string NombreClienteField;
        
        private string NumeroDocumentoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodigoComprobante
        {
            get
            {
                return this.CodigoComprobanteField;
            }
            set
            {
                this.CodigoComprobanteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodigoMensajeRetornoConsulta
        {
            get
            {
                return this.CodigoMensajeRetornoConsultaField;
            }
            set
            {
                this.CodigoMensajeRetornoConsultaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodigoSuministro
        {
            get
            {
                return this.CodigoSuministroField;
            }
            set
            {
                this.CodigoSuministroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DetalleConsulta
        {
            get
            {
                return this.DetalleConsultaField;
            }
            set
            {
                this.DetalleConsultaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DireccionCliente
        {
            get
            {
                return this.DireccionClienteField;
            }
            set
            {
                this.DireccionClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string DistritoCliente
        {
            get
            {
                return this.DistritoClienteField;
            }
            set
            {
                this.DistritoClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime FechaEmision
        {
            get
            {
                return this.FechaEmisionField;
            }
            set
            {
                this.FechaEmisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime FechaRegistroConsulta
        {
            get
            {
                return this.FechaRegistroConsultaField;
            }
            set
            {
                this.FechaRegistroConsultaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime FechaVencimiento
        {
            get
            {
                return this.FechaVencimientoField;
            }
            set
            {
                this.FechaVencimientoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdentificadorEntidadConsulta
        {
            get
            {
                return this.IdentificadorEntidadConsultaField;
            }
            set
            {
                this.IdentificadorEntidadConsultaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdentificadorTransaccion
        {
            get
            {
                return this.IdentificadorTransaccionField;
            }
            set
            {
                this.IdentificadorTransaccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MensajeRetornoConsulta
        {
            get
            {
                return this.MensajeRetornoConsultaField;
            }
            set
            {
                this.MensajeRetornoConsultaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal MontoAPagarConsulta
        {
            get
            {
                return this.MontoAPagarConsultaField;
            }
            set
            {
                this.MontoAPagarConsultaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string NombreCliente
        {
            get
            {
                return this.NombreClienteField;
            }
            set
            {
                this.NombreClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string NumeroDocumento
        {
            get
            {
                return this.NumeroDocumentoField;
            }
            set
            {
                this.NumeroDocumentoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClsPagoDeudaPeticion", Namespace="http://schemas.datacontract.org/2004/07/WSCobranzaSIELSE")]
    public partial class ClsPagoDeudaPeticion : object
    {
        
        private string AgenciaEntidadPagoField;
        
        private string ClaveUsuarioField;
        
        private string CodigoComprobanteField;
        
        private string CodigoSuministroField;
        
        private System.DateTime FechaPagoField;
        
        private string IdentificadorEntidadPagoField;
        
        private string IdentificadorTransaccionField;
        
        private string MedioPagoEntidadPagoField;
        
        private decimal MontoPagoField;
        
        private string UsuarioPagoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AgenciaEntidadPago
        {
            get
            {
                return this.AgenciaEntidadPagoField;
            }
            set
            {
                this.AgenciaEntidadPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ClaveUsuario
        {
            get
            {
                return this.ClaveUsuarioField;
            }
            set
            {
                this.ClaveUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodigoComprobante
        {
            get
            {
                return this.CodigoComprobanteField;
            }
            set
            {
                this.CodigoComprobanteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodigoSuministro
        {
            get
            {
                return this.CodigoSuministroField;
            }
            set
            {
                this.CodigoSuministroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime FechaPago
        {
            get
            {
                return this.FechaPagoField;
            }
            set
            {
                this.FechaPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdentificadorEntidadPago
        {
            get
            {
                return this.IdentificadorEntidadPagoField;
            }
            set
            {
                this.IdentificadorEntidadPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdentificadorTransaccion
        {
            get
            {
                return this.IdentificadorTransaccionField;
            }
            set
            {
                this.IdentificadorTransaccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MedioPagoEntidadPago
        {
            get
            {
                return this.MedioPagoEntidadPagoField;
            }
            set
            {
                this.MedioPagoEntidadPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal MontoPago
        {
            get
            {
                return this.MontoPagoField;
            }
            set
            {
                this.MontoPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UsuarioPago
        {
            get
            {
                return this.UsuarioPagoField;
            }
            set
            {
                this.UsuarioPagoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClsPagoDeudaRespuesta", Namespace="http://schemas.datacontract.org/2004/07/WSCobranzaSIELSE")]
    public partial class ClsPagoDeudaRespuesta : object
    {
        
        private string CodigoComprobanteField;
        
        private string CodigoIdentificadorPagoField;
        
        private int CodigoMensajeRetornoPagoField;
        
        private string CodigoSuministroField;
        
        private System.DateTime FechaRegistroPagoField;
        
        private string IdentificadorEntidadPagoField;
        
        private string IdentificadorTransaccionField;
        
        private string MensajeRetornoPagoField;
        
        private decimal MontoPagoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodigoComprobante
        {
            get
            {
                return this.CodigoComprobanteField;
            }
            set
            {
                this.CodigoComprobanteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodigoIdentificadorPago
        {
            get
            {
                return this.CodigoIdentificadorPagoField;
            }
            set
            {
                this.CodigoIdentificadorPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodigoMensajeRetornoPago
        {
            get
            {
                return this.CodigoMensajeRetornoPagoField;
            }
            set
            {
                this.CodigoMensajeRetornoPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodigoSuministro
        {
            get
            {
                return this.CodigoSuministroField;
            }
            set
            {
                this.CodigoSuministroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime FechaRegistroPago
        {
            get
            {
                return this.FechaRegistroPagoField;
            }
            set
            {
                this.FechaRegistroPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdentificadorEntidadPago
        {
            get
            {
                return this.IdentificadorEntidadPagoField;
            }
            set
            {
                this.IdentificadorEntidadPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdentificadorTransaccion
        {
            get
            {
                return this.IdentificadorTransaccionField;
            }
            set
            {
                this.IdentificadorTransaccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MensajeRetornoPago
        {
            get
            {
                return this.MensajeRetornoPagoField;
            }
            set
            {
                this.MensajeRetornoPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal MontoPago
        {
            get
            {
                return this.MontoPagoField;
            }
            set
            {
                this.MontoPagoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClsExtornoPagoPeticion", Namespace="http://schemas.datacontract.org/2004/07/WSCobranzaSIELSE")]
    public partial class ClsExtornoPagoPeticion : object
    {
        
        private string AgenciaEntidadExtornoField;
        
        private string ClaveUsuarioField;
        
        private string CodigoComprobanteField;
        
        private string CodigoIdentificadorPagoField;
        
        private int CodigoMotivoExtornoField;
        
        private string CodigoSuministroField;
        
        private System.DateTime FechaExtornoEntidadField;
        
        private string IdentificadorEntidadExtornoField;
        
        private string IdentificadorTransaccionField;
        
        private string MedioPagoEntidadExtornoField;
        
        private decimal MontoExtornoField;
        
        private string UsuarioExtornoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AgenciaEntidadExtorno
        {
            get
            {
                return this.AgenciaEntidadExtornoField;
            }
            set
            {
                this.AgenciaEntidadExtornoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ClaveUsuario
        {
            get
            {
                return this.ClaveUsuarioField;
            }
            set
            {
                this.ClaveUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodigoComprobante
        {
            get
            {
                return this.CodigoComprobanteField;
            }
            set
            {
                this.CodigoComprobanteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodigoIdentificadorPago
        {
            get
            {
                return this.CodigoIdentificadorPagoField;
            }
            set
            {
                this.CodigoIdentificadorPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodigoMotivoExtorno
        {
            get
            {
                return this.CodigoMotivoExtornoField;
            }
            set
            {
                this.CodigoMotivoExtornoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodigoSuministro
        {
            get
            {
                return this.CodigoSuministroField;
            }
            set
            {
                this.CodigoSuministroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime FechaExtornoEntidad
        {
            get
            {
                return this.FechaExtornoEntidadField;
            }
            set
            {
                this.FechaExtornoEntidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdentificadorEntidadExtorno
        {
            get
            {
                return this.IdentificadorEntidadExtornoField;
            }
            set
            {
                this.IdentificadorEntidadExtornoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdentificadorTransaccion
        {
            get
            {
                return this.IdentificadorTransaccionField;
            }
            set
            {
                this.IdentificadorTransaccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MedioPagoEntidadExtorno
        {
            get
            {
                return this.MedioPagoEntidadExtornoField;
            }
            set
            {
                this.MedioPagoEntidadExtornoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal MontoExtorno
        {
            get
            {
                return this.MontoExtornoField;
            }
            set
            {
                this.MontoExtornoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UsuarioExtorno
        {
            get
            {
                return this.UsuarioExtornoField;
            }
            set
            {
                this.UsuarioExtornoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClsExtornoPagoRespuesta", Namespace="http://schemas.datacontract.org/2004/07/WSCobranzaSIELSE")]
    public partial class ClsExtornoPagoRespuesta : object
    {
        
        private string CodigoComprobanteField;
        
        private string CodigoIdentificadorExtornoField;
        
        private int CodigoMensajeRetornoExtornoField;
        
        private string CodigoSuministroField;
        
        private System.DateTime FechaRegistroExtornoField;
        
        private string IdentificadorEntidadExtornoField;
        
        private string IdentificadorTransaccionField;
        
        private string MensajeRetornoExtornoField;
        
        private decimal MontoExtornoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodigoComprobante
        {
            get
            {
                return this.CodigoComprobanteField;
            }
            set
            {
                this.CodigoComprobanteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodigoIdentificadorExtorno
        {
            get
            {
                return this.CodigoIdentificadorExtornoField;
            }
            set
            {
                this.CodigoIdentificadorExtornoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodigoMensajeRetornoExtorno
        {
            get
            {
                return this.CodigoMensajeRetornoExtornoField;
            }
            set
            {
                this.CodigoMensajeRetornoExtornoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodigoSuministro
        {
            get
            {
                return this.CodigoSuministroField;
            }
            set
            {
                this.CodigoSuministroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime FechaRegistroExtorno
        {
            get
            {
                return this.FechaRegistroExtornoField;
            }
            set
            {
                this.FechaRegistroExtornoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdentificadorEntidadExtorno
        {
            get
            {
                return this.IdentificadorEntidadExtornoField;
            }
            set
            {
                this.IdentificadorEntidadExtornoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdentificadorTransaccion
        {
            get
            {
                return this.IdentificadorTransaccionField;
            }
            set
            {
                this.IdentificadorTransaccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MensajeRetornoExtorno
        {
            get
            {
                return this.MensajeRetornoExtornoField;
            }
            set
            {
                this.MensajeRetornoExtornoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal MontoExtorno
        {
            get
            {
                return this.MontoExtornoField;
            }
            set
            {
                this.MontoExtornoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClsConsultaPagoPeticion", Namespace="http://schemas.datacontract.org/2004/07/WSCobranzaSIELSE")]
    public partial class ClsConsultaPagoPeticion : object
    {
        
        private string AgenciaEntidadPagoField;
        
        private string ClaveUsuarioField;
        
        private string CodigoComprobanteField;
        
        private string CodigoSuministroField;
        
        private System.DateTime FechaPagoField;
        
        private string IdentificadorEntidadPagoField;
        
        private string IdentificadorTransaccionField;
        
        private string MedioPagoEntidadPagoField;
        
        private decimal MontoPagoField;
        
        private string UsuarioPagoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AgenciaEntidadPago
        {
            get
            {
                return this.AgenciaEntidadPagoField;
            }
            set
            {
                this.AgenciaEntidadPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ClaveUsuario
        {
            get
            {
                return this.ClaveUsuarioField;
            }
            set
            {
                this.ClaveUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodigoComprobante
        {
            get
            {
                return this.CodigoComprobanteField;
            }
            set
            {
                this.CodigoComprobanteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodigoSuministro
        {
            get
            {
                return this.CodigoSuministroField;
            }
            set
            {
                this.CodigoSuministroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime FechaPago
        {
            get
            {
                return this.FechaPagoField;
            }
            set
            {
                this.FechaPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdentificadorEntidadPago
        {
            get
            {
                return this.IdentificadorEntidadPagoField;
            }
            set
            {
                this.IdentificadorEntidadPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdentificadorTransaccion
        {
            get
            {
                return this.IdentificadorTransaccionField;
            }
            set
            {
                this.IdentificadorTransaccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MedioPagoEntidadPago
        {
            get
            {
                return this.MedioPagoEntidadPagoField;
            }
            set
            {
                this.MedioPagoEntidadPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal MontoPago
        {
            get
            {
                return this.MontoPagoField;
            }
            set
            {
                this.MontoPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string UsuarioPago
        {
            get
            {
                return this.UsuarioPagoField;
            }
            set
            {
                this.UsuarioPagoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClsConsultaPagoRespuesta", Namespace="http://schemas.datacontract.org/2004/07/WSCobranzaSIELSE")]
    public partial class ClsConsultaPagoRespuesta : object
    {
        
        private string CodigoComprobanteField;
        
        private string CodigoIdentificadorPagoField;
        
        private int CodigoMensajeRetornoConsultaPagoField;
        
        private string CodigoSuministroField;
        
        private System.DateTime FechaRegistroConsultaPagoField;
        
        private System.DateTime FechaRegistroPagoField;
        
        private string IdentificadorEntidadPagoField;
        
        private string IdentificadorTransaccionField;
        
        private string MensajeRetornoConsultaPagoField;
        
        private decimal MontoPagoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodigoComprobante
        {
            get
            {
                return this.CodigoComprobanteField;
            }
            set
            {
                this.CodigoComprobanteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodigoIdentificadorPago
        {
            get
            {
                return this.CodigoIdentificadorPagoField;
            }
            set
            {
                this.CodigoIdentificadorPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CodigoMensajeRetornoConsultaPago
        {
            get
            {
                return this.CodigoMensajeRetornoConsultaPagoField;
            }
            set
            {
                this.CodigoMensajeRetornoConsultaPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CodigoSuministro
        {
            get
            {
                return this.CodigoSuministroField;
            }
            set
            {
                this.CodigoSuministroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime FechaRegistroConsultaPago
        {
            get
            {
                return this.FechaRegistroConsultaPagoField;
            }
            set
            {
                this.FechaRegistroConsultaPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime FechaRegistroPago
        {
            get
            {
                return this.FechaRegistroPagoField;
            }
            set
            {
                this.FechaRegistroPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdentificadorEntidadPago
        {
            get
            {
                return this.IdentificadorEntidadPagoField;
            }
            set
            {
                this.IdentificadorEntidadPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string IdentificadorTransaccion
        {
            get
            {
                return this.IdentificadorTransaccionField;
            }
            set
            {
                this.IdentificadorTransaccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string MensajeRetornoConsultaPago
        {
            get
            {
                return this.MensajeRetornoConsultaPagoField;
            }
            set
            {
                this.MensajeRetornoConsultaPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal MontoPago
        {
            get
            {
                return this.MontoPagoField;
            }
            set
            {
                this.MontoPagoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSSielse.ISCobranza")]
    public interface ISCobranza
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCobranza/ConsultaDeuda", ReplyAction="http://tempuri.org/ISCobranza/ConsultaDeudaResponse")]
        WSSielse.ClsConsultaDeudaRespuesta ConsultaDeuda(WSSielse.ClsConsultaDeudaPeticion consultaDeudaPeticion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCobranza/ConsultaDeuda", ReplyAction="http://tempuri.org/ISCobranza/ConsultaDeudaResponse")]
        System.Threading.Tasks.Task<WSSielse.ClsConsultaDeudaRespuesta> ConsultaDeudaAsync(WSSielse.ClsConsultaDeudaPeticion consultaDeudaPeticion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCobranza/PagoDeuda", ReplyAction="http://tempuri.org/ISCobranza/PagoDeudaResponse")]
        WSSielse.ClsPagoDeudaRespuesta PagoDeuda(WSSielse.ClsPagoDeudaPeticion pagoDeudaPeticion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCobranza/PagoDeuda", ReplyAction="http://tempuri.org/ISCobranza/PagoDeudaResponse")]
        System.Threading.Tasks.Task<WSSielse.ClsPagoDeudaRespuesta> PagoDeudaAsync(WSSielse.ClsPagoDeudaPeticion pagoDeudaPeticion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCobranza/ExtornoPago", ReplyAction="http://tempuri.org/ISCobranza/ExtornoPagoResponse")]
        WSSielse.ClsExtornoPagoRespuesta ExtornoPago(WSSielse.ClsExtornoPagoPeticion extornoPagoPeticion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCobranza/ExtornoPago", ReplyAction="http://tempuri.org/ISCobranza/ExtornoPagoResponse")]
        System.Threading.Tasks.Task<WSSielse.ClsExtornoPagoRespuesta> ExtornoPagoAsync(WSSielse.ClsExtornoPagoPeticion extornoPagoPeticion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCobranza/ConsultaPago", ReplyAction="http://tempuri.org/ISCobranza/ConsultaPagoResponse")]
        WSSielse.ClsConsultaPagoRespuesta ConsultaPago(WSSielse.ClsConsultaPagoPeticion consultaPagoPeticion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISCobranza/ConsultaPago", ReplyAction="http://tempuri.org/ISCobranza/ConsultaPagoResponse")]
        System.Threading.Tasks.Task<WSSielse.ClsConsultaPagoRespuesta> ConsultaPagoAsync(WSSielse.ClsConsultaPagoPeticion consultaPagoPeticion);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface ISCobranzaChannel : WSSielse.ISCobranza, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SCobranzaClient : System.ServiceModel.ClientBase<WSSielse.ISCobranza>, WSSielse.ISCobranza
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SCobranzaClient() : 
                base(SCobranzaClient.GetDefaultBinding(), SCobranzaClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISCobranza.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SCobranzaClient(EndpointConfiguration endpointConfiguration) : 
                base(SCobranzaClient.GetBindingForEndpoint(endpointConfiguration), SCobranzaClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SCobranzaClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SCobranzaClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SCobranzaClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SCobranzaClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SCobranzaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public WSSielse.ClsConsultaDeudaRespuesta ConsultaDeuda(WSSielse.ClsConsultaDeudaPeticion consultaDeudaPeticion)
        {
            return base.Channel.ConsultaDeuda(consultaDeudaPeticion);
        }
        
        public System.Threading.Tasks.Task<WSSielse.ClsConsultaDeudaRespuesta> ConsultaDeudaAsync(WSSielse.ClsConsultaDeudaPeticion consultaDeudaPeticion)
        {
            return base.Channel.ConsultaDeudaAsync(consultaDeudaPeticion);
        }
        
        public WSSielse.ClsPagoDeudaRespuesta PagoDeuda(WSSielse.ClsPagoDeudaPeticion pagoDeudaPeticion)
        {
            return base.Channel.PagoDeuda(pagoDeudaPeticion);
        }
        
        public System.Threading.Tasks.Task<WSSielse.ClsPagoDeudaRespuesta> PagoDeudaAsync(WSSielse.ClsPagoDeudaPeticion pagoDeudaPeticion)
        {
            return base.Channel.PagoDeudaAsync(pagoDeudaPeticion);
        }
        
        public WSSielse.ClsExtornoPagoRespuesta ExtornoPago(WSSielse.ClsExtornoPagoPeticion extornoPagoPeticion)
        {
            return base.Channel.ExtornoPago(extornoPagoPeticion);
        }
        
        public System.Threading.Tasks.Task<WSSielse.ClsExtornoPagoRespuesta> ExtornoPagoAsync(WSSielse.ClsExtornoPagoPeticion extornoPagoPeticion)
        {
            return base.Channel.ExtornoPagoAsync(extornoPagoPeticion);
        }
        
        public WSSielse.ClsConsultaPagoRespuesta ConsultaPago(WSSielse.ClsConsultaPagoPeticion consultaPagoPeticion)
        {
            return base.Channel.ConsultaPago(consultaPagoPeticion);
        }
        
        public System.Threading.Tasks.Task<WSSielse.ClsConsultaPagoRespuesta> ConsultaPagoAsync(WSSielse.ClsConsultaPagoPeticion consultaPagoPeticion)
        {
            return base.Channel.ConsultaPagoAsync(consultaPagoPeticion);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISCobranza))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISCobranza))
            {
                return new System.ServiceModel.EndpointAddress("https://elsx007.electrosur.com.pe/WSCobranzaOnline/SCobranza.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SCobranzaClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISCobranza);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SCobranzaClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISCobranza);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISCobranza,
        }
    }
}
